name: 'Deploy AWS Lambda function'
description: 'Update the code of an AWS Lambda function'
author: 'Yves Gurcan/Jack Johnson'
branding:
  icon: 'layers'
  color: 'orange'
inputs:
  package:
    description: 'Zip package of Lambda and dependencies'
    default: ''
  function-name:
    description: 'Name of Lambda function'
    default: ''
  AWS_SECRET_KEY:
    description: 'AWS secret key'
    default: ''
  AWS_SECRET_ID:
    description: 'AWS secret key ID'
    default: ''
  AWS_REGION:
    description: 'AWS region of the Lambda'
    default: ''
  environment:
    description: 'The environment being deployed'
    default: ''
  
runs:
  using: 'node12'
  main: 'index.js'
